# Site settings
title: Raquel Sweet - Engineering Portfolio
email: res397@cornell.edu
description: >- # this means to ignore newlines until "baseurl:"
  A brief description of your portfolio and your skills.
baseurl: "/Raquel-Sweet-Portfolio" # the subpath of your site, e.g. /blog. For GitHub Pages user sites, this is often blank.
url: "https://res397-svg.github.io" # the base hostname & protocol for your site, e.g. http://example.com. For GitHub Pages, it will be like https://username.github.io

# Author/Social
author:
  name: Raquel Sweet # Update this from "Your Name"
  # twitter_username: yourtwitter
  # github_username:  yourgithub

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub Flavored Markdown
  syntax_highlighter: rouge

# Collections
collections:
  projects:
    output: true # This will generate a page for each project
    permalink: /projects/:name/ # URL structure for individual project pages
  reports:
    output: true # This will generate a page for each report
    permalink: /reports/:name/ # URL structure for individual report pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically
# added to the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/files/project_writeups.docx

plugins:
  - jekyll-feed

include:
  - assets/covers
  - assets/files
